"""PDF V2 Pipeline package."""

from .config import (
    LLM_BASE_URL,
    LLM_API_KEY,
    LLM_MODEL,
    EMBEDDING_MODEL,
    MAX_BULLETS,
    MAX_BULLET_CHARS,
    MAX_ITERATIONS,
    SCRAPING_SOURCES,
    CONTENT_CACHE_DIR,
    HISTORY_DB_DIR,
    HISTORY_DB_ENABLED,
)